/*
 * Problem: Find the Difference
 * Description: You are given two strings s and t. String t is generated by randomly shuffling
 * string s and then adding one more letter at a random position.
 * Return the letter that was added to t.
 * Link: https://leetcode.com/problems/find-the-difference/
 *
 * Author: Raghav Jatic
 * Date: 20th December 2025
 */

#include <iostream>
#include <vector>
#include <string>
using namespace std;

class Solution {
public:
    char findTheDifference(string s, string t) {
        int len=s.size();
        vector<int> hash(26,0);
        for(int i=0;i<len;i++)
        {
            char c=s[i];
            hash[c-'a']+=1;
        }

        int len2=t.size();
        for(int i=0;i<len2;i++)
        {
            char c=t[i];
            if(hash[c-'a']==0)
            return t[i];
            else
            hash[c-'a']-=1;
        }
        return 0;
    }
};

int main() {
    Solution sol;

    cout << sol.findTheDifference("abcd", "abcde") << endl; // Expected: e
    cout << sol.findTheDifference("", "y") << endl;         // Expected: y
    cout << sol.findTheDifference("aabb", "ababb") << endl; // Expected: b

    return 0;
}
